name: Create Layer

on:
  workflow_dispatch:
    inputs:
      directory:
        description: directory
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  create_layer:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          sparse-checkout: |
            ${{ inputs.directory }}
            create-layer.sh

      - uses: actions/setup-python@v5
        with:
          python-version-file: ${{ inputs.directory }}/.python-version

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: echo version
        working-directory: ${{ inputs.directory }}
        run: |
          ../create-layer.sh
